#ifndef ERROR_CODES_H
# define ERROR_CODES_H

# define MALLOC_ERROR -1
# define SDL_INIT_ERROR -2
# define IMG_INIT_ERROR -3
# define WINDOW_CREATE_ERROR -4
# define RENDER_INIT_ERROR -5
# define TEXTURE_LOAD_ERROR -6
# define TEXTURE_LOCK_ERROR -7
# define KERNEL_FILE_OPEN_ERROR -8

/*
** ---parse_macro---
*/

#define INVALID_ARGUMENTS -11
#define INVALID_TYPE -12
#define INVALID_ARGUMENTS_IN_LINE -13
#define MISS_NEW_LINE -14
#define WRONG_FOV -15
#define WRONG_HEIGHT -16
#define WRONG_RADIUS -17
#define WRONG_REFLECTION -18
#define WRONG_INTENSITY -19

#endif
