#ifndef ERROR_CODES_H
# define ERROR_CODES_H

# define MALLOC_ERROR -1
# define SDL_INIT_ERROR -2
# define IMG_INIT_ERROR -3
# define WINDOW_CREATE_ERROR -4
# define RENDER_INIT_ERROR -5
# define TEXTURE_LOAD_ERROR -6
# define TEXTURE_LOCK_ERROR -7
# define KERNEL_FILE_OPEN_ERROR -8

#define INVALID_ARGUMENTS -11
#define INVALID_TYPE -12
#define INVALID_ARGUMENTS_IN_LINE -13


#endif
